name: Build Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run build:win

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: dist/*
